# Generated by Django 5.1.4 on 2024-12-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_customer_options_alter_customer_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="mobile_number",
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
