# Generated by Django 5.1.4 on 2024-12-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_customer_mobile_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="mobile_number",
        ),
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.IntegerField(default=0, max_length=10, unique=True),
        ),
    ]
