# Generated by Django 5.1.4 on 2024-12-18 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="id",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="name",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="password",
        ),
        migrations.AddField(
            model_name="seller",
            name="owner_name",
            field=models.CharField(default="Default Owner Name", max_length=255),
        ),
        migrations.AddField(
            model_name="seller",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
        migrations.AddField(
            model_name="seller",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="seller",
            name="seller_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="seller",
            name="shop_address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="seller",
            name="shop_name",
            field=models.CharField(max_length=255),
        ),
    ]
