# Generated by Django 5.1.4 on 2024-12-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0003_category_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="seller_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
