# Generated by Django 5.1.4 on 2024-12-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0004_alter_seller_seller_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="user",
        ),
    ]
