# Generated by Django 5.1.4 on 2024-12-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0005_remove_seller_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="password",
            field=models.CharField(default="", max_length=255),
        ),
    ]
