# Generated by Django 5.1.4 on 2024-12-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0008_alter_category_image_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
