# Generated by Django 5.1.4 on 2025-01-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0012_alter_seller_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="is_seller",
            field=models.BooleanField(default=True),
        ),
    ]
