# Generated by Django 5.1.4 on 2025-01-15 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0013_seller_is_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="phone",
            field=models.CharField(
                default="0000000000",
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_mobile_number",
                        message="Mobile number must be exactly 10 digits.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
    ]
