# Generated by Django 5.1.4 on 2025-01-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0014_alter_seller_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
