# Generated by Django 5.1.4 on 2025-01-04 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cart", "0001_initial"),
        ("base", "0007_alter_customer_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.customer",
            ),
        ),
    ]
