# Generated by Django 5.1.4 on 2025-01-18 20:05

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="temporary",
                editable=False,
                populate_from="product.name",
                unique=True,
            ),
        ),
    ]
