# Generated by Django 5.1.4 on 2025-01-21 13:36

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_slug"),
        ("seller", "0015_product_is_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="order",
            name="seller_id",
        ),
        migrations.AlterField(
            model_name="order",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="product.name", unique=True
            ),
        ),
        migrations.CreateModel(
            name="Orderitems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderitems",
                        to="order.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="seller.product"
                    ),
                ),
            ],
        ),
    ]
