# Generated by Django 5.1.4 on 2025-01-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_remove_order_product_remove_order_quantity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="custid",
            new_name="user",
        ),
    ]
