# Generated by Django 5.1.4 on 2025-01-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_rename_custid_address_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="slug",
        ),
    ]
